### ISSUE TITLE
Applying Encoding to new, unseen data

### ISSUE THREAD

**Issue by harryjulian** [ak-gupta/bayte#7]
Hi there,

Big fan of the implementations in this package, I've found it really useful!

One problem though, I'm not sure how to train an encoder (and a model) on a training dataset, and then apply to an unseen dataset. Any intuition?

**Comment by ak-gupta** [comment]
Hey @harryjulian! Sorry I didn't see this earlier. I _think_ you're looking for the `transform` method (see [here](https://bayte.readthedocs.io/en/latest/how-to/encode.html#basic-usage)). The `transform` method uses the fitted estimator to encode the new, supplied dataset. If you're asking about new categorical levels (i.e. a value for your nominal categorical that _doesn't_ exist in the training dataset), the encoder will use the prior distribution to encode that value (see [this](https://bayte.readthedocs.io/en/latest/explanation/algorithm.html#id2) footnote).
